name: Assign User
description: Assigns a user to an issue or pull request

inputs:
  number:
    description: 'Who to greet'
    required: true
    default: ${{ github.event.number }}
  assignee:
    description: 'Who to greet'
    required: true
    default: 'austenstone'

runs:
  using: "composite"
  steps:
    - run: gh issue edit ${{ inputs.number }} --add-assignee ${{ inputs.assignee }}
      shell: bash
