blank_issues_enabled: true
contact_links:
  - name: Austen Stone
    url: https://austen.info
    about: Contact me and check out my portfolio!
  - name: GitHub Community Support
    url: https://github.com/orgs/community/discussions
    about: Please ask and answer questions here.
