name: Concurrency

on:
  push:
  pull_request:
  workflow_dispatch:

concurrency:
  group: 'staging'
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: jakejarvis/wait-action@master
        with:
          time: '30s'

      - name: Run a one-line script
        run: echo Hello, world!

      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.
