name: Docker Build & Push
description: "Builds and pushes a Docker image to Docker Hub & GitHub Package Registry"

inputs:
  username:
    description: 'DockerHub username'
    default: miltonlaxer
    required: false
  repo_owner:
    description: 'Github repository owner'
    default: ${{ github.event.repository.owner.login }}
    required: false
  repo:
    description: 'GitHub token for ghcr.io'
    default: ${{ github.event.repository.name }}
    required: false
outputs:
  tags:
    description: "The image tags"
    value: ${{ steps.meta.outputs.tags }}
  labels:
    description: "The image labels"
    value: ${{ steps.meta.outputs.labels }}

runs:
  using: "composite"

  steps:
    - uses: docker/metadata-action@v4
      id: meta
      with:
        tags: |
          type=schedule
          type=ref,event=branch
          type=ref,event=tag
          type=ref,event=pr
          type=sha,format=long
        images: |
          ${{ inputs.username }}/${{ inputs.repo }}
          ghcr.io/${{ inputs.repo_owner }}/${{ inputs.repo }}
    - uses: docker/build-push-action@v3
      with:
        context: .
        push: ${{ github.event_name != 'pull_request' }}
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}
