name: Build

on:
  workflow_call:
    inputs:
      out_dir:
        default: 'dist'
        required: true
        type: string

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/node-setup-install
      - run: npm run build
      - uses: actions/upload-artifact@v3
        with:
          name: dist
          path: ${{ inputs.out_dir }}


