name: Docker Deploy

on:
  workflow_call:
    inputs:
      artifact-name:
        default: "dist"
        required: false
        type: string
    outputs:
      tags:
        description: "The first output string"
        value: ${{ jobs.docker.outputs.tags }}
      labels:
        description: "The first output string"
        value: ${{ jobs.docker.outputs.labels }}

env:
  DOCKERHUB_USERNAME: miltonlaxer

jobs:
  docker:
    environment:
      name: docker
      url: https://hub.docker.com/r/${{ env.DOCKERHUB_USERNAME }}/${{ github.event.repository.name }}
    runs-on: ubuntu-latest
    outputs:
      tags: ${{ steps.meta.outputs.tags }}
      labels: ${{ steps.meta.outputs.labels }}
    steps:
      - uses: docker/setup-qemu-action@v2
      - uses: docker/setup-buildx-action@v2
      - uses: docker/login-action@v2
        with:
          username: ${{ env.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - uses: actions/checkout@v3
      - uses: actions/download-artifact@v3
        with:
          name: ${{ inputs.artifact-name }}
          path: dist/${{ github.event.repository.name }}

      - uses: docker/metadata-action@v4
        id: meta
        with:
          tags: |
            type=schedule
            type=ref,event=branch
            type=ref,event=tag
            type=ref,event=pr
            type=sha,format=long
          images: |
            ${{ env.DOCKERHUB_USERNAME }}/${{ github.event.repository.name }}
            ghcr.io/${{ github.event.repository.owner.login }}/${{ github.event.repository.name }}
      - uses: docker/build-push-action@v3
        with:
          context: .
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}

  trivy:
    needs: [docker]
    uses: ./.github/workflows/trivy.yml
    with:
      image-ref: ${{ needs.docker.outputs.tags }}
    secrets: inherit
