name: Release

on:
  workflow_call:
    inputs:
      dist:
        default: 'dist'
        required: true
        type: string

jobs:
  deploy:
    name: Release
    permissions:
      contents: write
    runs-on: ubuntu-latest

    steps:
    - uses: actions/download-artifact@v3
      with:
        name: ${{ inputs.dist }}
    - uses: softprops/action-gh-release@v1
      with:
        files: .

