name: Release

on:
  workflow_call:

jobs:
  deploy:
    name: Release
    permissions:
      contents: write
    runs-on: ubuntu-latest

    steps:
    - uses: actions/download-artifact@v3
      with:
        name: dist
    - uses: softprops/action-gh-release@v1
      with:
        files: .

