name: Build

on:
  workflow_call:

env:
  dist: dist/${{ github.event.repository.name }}

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/node-setup-install
      - run: npm run build -- --base-href /${{ github.event.repository.name }}/
      - run: cp ${{ env.dist }}/index.html ${{ env.dist }}/404.html
      - uses: actions/upload-artifact@v3
        with:
          name: dist
          path: ${{ env.dist }}


