name: Change Dependabot Branch Base 🔄

on:
  workflow_call:
    inputs:
      length:
        description: 'The length of the branch name to truncate to'
        default: 125
        type: number
      prefix:
        description: 'The prefix to add to the truncated branch name'
        default: ''
        type: string
  # pull_request:

jobs:
  dependabot:
    runs-on: ubuntu-latest
    if: github.event.pull_request.user.login == 'dependabot[bot]'
    steps:
      - uses: actions/checkout@v4

      - id: truncate
        run: |
          BRANCH_NAME="${{ github.head_ref }}"
          TRUNCATED=${BRANCH_NAME:0:${{ inputs.length }}}
          echo "truncated=${{ inputs.prefix }}$TRUNCATED" >> $GITHUB_OUTPUT

      - run: |
          git checkout -b "${{ steps.truncate.outputs.truncated }}"
          git push origin "${{ steps.truncate.outputs.truncated }}"
        
      - run: gh pr edit "${{ github.event.pull_request.html_url }}" --base "${{ steps.truncate.outputs.truncated }}"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
