name: Dependabot Rebase All

on:
  workflow_call:
    inputs:
      repo:
        default: ${{ github.repository }}
        type: string
      owner:
        type: string
      token:
        default: ${{ github.token }}
        type: string
      action:
        default: rebase
        type: string

jobs:
  dependabot:
    runs-on: ubuntu-latest
    steps:
      - name: Get Scope
        id: scope
        run: |
          if [ -n "${{ inputs.owner }}" ]; then
            echo "SCOPE=--owner ${{ inputs.owner }}" >> $GITHUB_OUTPUT
          else
            echo "SCOPE=--repo ${{ inputs.repo }}" >> $GITHUB_OUTPUT
          fi
      - run: |
          gh search prs \
            ${{ steps.scope.outputs.SCOPE }} \
            --state open \
            --label dependencies \
            --limit 200 \
            --json "url" --jq ".[] | .url" \
          | xargs -n 1 -I{} \
            gh pr comment -b "@dependabot ${{ inputs.action }}" {}
        env:
          GH_TOKEN: ${{ github.token || inputs.token }}
