name: Change Dependabot Branch Base 🔄

on:
  workflow_call:
    inputs:
      length:
        description: 'The length of the branch name to truncate to'
        default: 125
        type: number
      prefix:
        description: 'The prefix to add to the truncated branch name'
        default: ''
        type: string
  # pull_request:

jobs:
  dependabot:
    runs-on: ubuntu-latest
    if: github.event.pull_request.user.login == 'dependabot[bot]'
    steps:
      - uses: actions/checkout@v4

      - id: truncate
        run: |
          BRANCH_NAME="${{ github.head_ref }}"
          TRUNCATED=${BRANCH_NAME:0:${{ inputs.length }}}
          echo "truncated=${{ inputs.prefix }}$TRUNCATED" >> $GITHUB_OUTPUT

      - run: |
          git branch
          git checkout -b "${{ steps.truncate.outputs.truncated }}"
          git push origin "${{ steps.truncate.outputs.truncated }}"
        
      - name: Close existing PR and create new one
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh pr close "${{ github.event.pull_request.number }}"
          gh pr create \
            --title "${{ github.event.pull_request.title }}" \
            --body "${{ github.event.pull_request.body }}" \
            --base "${{ github.event.pull_request.base.ref }}" \
            --head "${{ steps.truncate.outputs.truncated }}"
            --add-label ${{ join(github.event.pull_request.labels.*.name, ',') }}