name: Change Dependabot Branch Base 🔄
on: pull_request

permissions:
  pull-requests: write

jobs:
  dependabot:
    runs-on: ubuntu-latest
    if: github.event.pull_request.user.login == 'dependabot[bot]'
    steps:
      - name: Checkout repository
        uses: actions/checkout

      - name: Truncate branch name
        id: truncate
        run: |
          BRANCH_NAME="${{ github.head_ref }}"
          TRUNCATED=${BRANCH_NAME:0:126}
          echo "truncated=$TRUNCATED" >> $GITHUB_OUTPUT

      - name: Create and push new branch
        run: |
          git checkout -b "${{ steps.truncate.outputs.truncated }}"
          git push origin "${{ steps.truncate.outputs.truncated }}"
        
      - name: Update PR base branch
        run: gh pr edit "${{ github.event.pull_request.html_url }}" --base "${{ steps.truncate.outputs.truncated }}"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}