name: "Dispatch"

on:
  push:
  workflow_dispatch:

jobs:
  dispatch:
    runs-on: ubuntu-latest
    steps:
      - run: |
          repos=("austenstone/angular-codespace")
          for i in "${repos[@]}";do gh workflow run --repo $i build-test-deploy.yml;done          
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}