name: "Dispatch"

on:
  push:
  workflow_dispatch:
  workflow_call:
    inputs:
      repos:
        default: 'austenstone/angular-codespace'
        required: true
        type: string
    

jobs:
  dispatch:
    runs-on: ubuntu-latest
    env:
      REPOS: |
        (
          ${{ inputs.repos }}
        )
    steps:
      - name: "Dispatch Repos"
        run: |
          repos=${{ env.REPOS }}
          for repo in "${repos[@]}"; do
            gh workflow run --repo $repo build-test-deploy.yml
          done
        shell: bash
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}