name: "Dispatch"

on:
  workflow_call:
    inputs:
      repos:
        required: true
        type: string
      workflow:
        required: true
        type: string
    

jobs:
  dispatch:
    runs-on: ubuntu-latest
    env:
      REPOS: |
        (
          ${{ inputs.repos }}
        )
    steps:
      - name: "Dispatch Repos"
        run: |
          repos=${REPOS}
          for repo in "${repos[@]}"; do
            gh workflow run --repo $repo ${WORKFLOW}
          done
        shell: bash
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}