name: "Dispatch"

on:
  push:
  workflow_dispatch:

jobs:
  dispatch:
    runs-on: ubuntu-latest
    env:
      REPOS: ("austenstone/angular-codespace")
    steps:
      - run: for i in "${REPOS[@]}";do gh workflow run --repo $i build-test-deploy.yml;done
        shell: bash
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}