name: NodeJS

on:
  workflow_call:

env:
  dist: dist/${{ github.event.repository.name }}

jobs:
  build:
    name: Build ⚒️
    uses: ./.github/workflows/build.yml

  test:
    name: Test 🧪
    needs: [build]
    # strategy:
    #   matrix:
    #     os: [ubuntu-latest, windows-latest, macos-latest]
    uses: ./.github/workflows/test.yml

  deploy:
    name: Deploy 🚀
    needs: [build, test]
    if: github.ref == 'refs/heads/main'
    uses: ./.github/workflows/deploy.yml

  release:
    if: startsWith(github.ref, 'refs/tags/')
    needs: [build, test]
    name: Release 🚢
    uses: ./.github/workflows/release.yml
