name: NodeJS

on:
  workflow_call:
    inputs:
      runs-on:
        default: 'ubuntu-latest'
        required: false
        type: string
      node-version:
        default: '16.x'
        required: false
        type: string

jobs:
  ci:
    runs-on: ${{ inputs.runs-on }}

    steps:
      - uses: actions/checkout@v3
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: ${{ inputs.node-version }}
      - uses: austenstone/.github/.github/actions/npm-ci-cache@main
      # - run: npm run lint
      - run: npm run build
      - run: npm test
