name: Psalm Security Scan

on:
  workflow_call:
    inputs:
      sarif_file_name:
        default: 'results.sarif'
        type: string

jobs:
  psalm:
    name: Psalm
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Check file existence
        id: check_files
        uses: andstor/file-existence-action@v2
        with:
          files: composer.json
      - if: steps.check_files.outputs.files_exists == 'true'
        run: |
          COMPOSER_COMMAND="composer install --no-scripts --no-progress"
          echo "::group::$COMPOSER_COMMAND"
          $COMPOSER_COMMAND
          echo "::endgroup::"

      - run: composer require --dev vimeo/psalm
      - run: ./vendor/bin/psalm --version
      - run: ./vendor/bin/psalm --init
      - run: ./vendor/bin/psalm --output-format=github --taint-analysis --report=${{ inputs.sarif_file_name }} $*
      
      - name: Upload SARIF file
        uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: ${{ inputs.sarif_file_name }}
