name: Psalm Security Scan

on:
  workflow_call:

jobs:
  psalm:
    name: Psalm
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        
      - name: Check file existence
        id: check_files
        uses: andstor/file-existence-action@v1
        with:
          files: "assets/${{ env.URL }}"

      - run: composer require --dev vimeo/psalm
        if: steps.check_files.outputs.files_exists == 'true'

      - run: ./vendor/bin/psalm --init
      - run: ./vendor/bin/psalm
