name: "Dispatch"

on:
  push:

jobs:
  dispatch:
    runs-on: ubuntu-latest
    steps:
      - run: gh workflow run --repo austenstone/angular-codespace build-test-deploy.yml
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}