name: Release

on:
  workflow_call:

env:
  dist: dist/${{ github.event.repository.name }}

jobs:
  deploy:
    name: Release
    permissions:
      contents: write
    runs-on: ubuntu-latest

    steps:
    - uses: actions/download-artifact@v3
      with:
        name: dist
        path: ${{ env.dist }}
    - uses: softprops/action-gh-release@v1
      with:
        files: ${{ env.dist }}

