name: Re-run failed jobs

on:
  workflow_call:
    inputs:
      run_id:
        default: ${{ github.run_id }}
        type: string

jobs:
  rerun:
    runs-on: ubuntu-latest
    steps:
      - run: gh run rerun ${{ github.run_id }} --failed
        env:
            GH_TOKEN: ${{ github.token }}
