name: Scoped Secrets

on:
  workflow_call:

jobs:
  secret-print:
    runs-on: ubuntu-latest
    steps:
      - name: Print Secret
        run: echo ${{ secrets.SUPER_SECRET }}
      - name: Print Variable
        run: echo ${{ vars.SUPER_SECRET }}
