name: Slack Failed Checks

on:
  workflow_call:
    inputs:
      notify_when:
        required: false
        type: string
    secrets:
      envPAT:
        required: true

jobs:
  notify-slack:
    runs-on: ubuntu-latest
    if: always()
    steps:
      - name: Report Status
        if: always()
        uses: ravsamhq/notify-slack-action@v1
        with:
          status: ${{ job.status }} # required
          notify_when: ${{ inputs.notify_when || 'failure' }}
          notification_title: '{workflow} has {status_message}'
          message_format: '{emoji} *{workflow}* {status_message} in <{repo_url}|{repo}>'
          footer: 'Linked to Repo <{repo_url}|{repo}>'
          mention_users: 'U0160UUNH8S,U0080UUAA9N'
          mention_users_when: 'failure,warnings'
          mention_groups: 'SAZ94GDB8'
          mention_groups_when: 'failure,warnings'
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.ACTION_MONITORING_SLACK }}
