# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Trivy
on:
  workflow_call:
    inputs:
      image-ref:
        required: true
        type: string

permissions:
  contents: read

jobs:
  trivy:
    runs-on: "ubuntu-18.04"
    permissions:
      contents: read # for actions/checkout to fetch code
      security-events: write # for github/codeql-action/upload-sarif to upload SARIF results
    steps:
      - id: truncate
        run: echo "::set-output name=image-ref::$(echo "${{ inputs.image-ref }}" | head -1)"
      - name: Run Trivy vulnerability scanner for image ${{ inputs.image-ref }}
        uses: aquasecurity/trivy-action@7b7aa264d83dc58691451798b4d117d53d21edfe
        with:
          image-ref: ${{ steps.truncate.outputs.image-ref }}
          format: 'template'
          template: '@/contrib/sarif.tpl'
          output: 'trivy-results.sarif'
          severity: 'CRITICAL,HIGH'

      - name: Upload Trivy scan results to GitHub Security tab
        uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: 'trivy-results.sarif'
